### ISSUE TITLE
CAR-2015-07-001 Missing Coverage and Technique

### ISSUE THREAD

**Issue by th3y3ti** [mitre-attack/car#31]
CAR-2015-07-001 is missing the coverage section and the associated Tactics/Techniques. Not a big deal, I can code around the "key error" from my YAML parser but figured others would have similar issues.

**Comment by ikiril01** [comment]
Hi @th3y3ti - the omission of coverage for CAR-2015-07-001 is intentional, because unlike other analytics it is oriented towards providing generic situational awareness around user login activity, and therefore there aren't any corresponding ATT&CK techniques that it covers. If you have any other ideas on this please let us know.

**Comment by th3y3ti** [comment]
Thanks... ya, I was looking at 2019-07-001 on accident and it had a
technique. I realized after submitting. :)

I will say I also encountered some charmap issue with 3 or 4 of the yaml
files. I can send you the names/numbers if you are interested. I just
converted them to utf 8 before opening so no biggie.

**Comment by ikiril01** [comment]
Ah, no worries :) Sure, if you could share the charmap issues you found, that would be appreciated.
